# Generated by Django 6.1.1 on 2026-09-25 12:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('complaints', '0001_initial'),
        ('genai_pipeline', '0002_genaianalysis_cache_hit_tokens'),
    ]

    operations = [
        migrations.CreateModel(
            name='ValidationResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('independent_expected', models.JSONField(default=dict)),
                ('genai_view_expected', models.JSONField(default=dict)),
                ('checks', models.JSONField(default=list)),
                ('score', models.PositiveSmallIntegerField()),
                ('agreement_rate', models.FloatField()),
                ('decision', models.CharField(choices=[('verified', 'Verified'), ('manual_review', 'Manual Review')], max_length=20)),
                ('review_reasons', models.JSONField(default=list)),
                ('final_resolution', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('analysis', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='validations', to='genai_pipeline.genaianalysis')),
                ('complaint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='validations', to='complaints.complaint')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
