# Generated by Django 6.1.1 on 2026-09-25 12:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('complaints', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PromptTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('version', models.CharField(max_length=20)),
                ('system_prompt', models.TextField()),
                ('user_prompt', models.TextField()),
                ('description', models.CharField(blank=True, max_length=255)),
                ('is_active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GenAIAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(max_length=50)),
                ('model', models.CharField(max_length=100)),
                ('generation_config', models.JSONField(default=dict)),
                ('request_messages', models.JSONField(default=list)),
                ('retrieved_chunks', models.JSONField(default=list)),
                ('policy_versions', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('success', 'Success'), ('failed', 'Failed')], max_length=20)),
                ('attempts', models.JSONField(default=list)),
                ('raw_response', models.TextField(blank=True)),
                ('output', models.JSONField(blank=True, null=True)),
                ('validation_issues', models.JSONField(default=list)),
                ('error', models.TextField(blank=True)),
                ('prompt_tokens', models.PositiveIntegerField(default=0)),
                ('completion_tokens', models.PositiveIntegerField(default=0)),
                ('latency_ms', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('complaint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='genai_analyses', to='complaints.complaint')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('prompt_template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='analyses', to='genai_pipeline.prompttemplate')),
            ],
            options={
                'verbose_name_plural': 'GenAI analyses',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='prompttemplate',
            constraint=models.UniqueConstraint(fields=('name', 'version'), name='unique_prompt_version'),
        ),
    ]
