# Generated by Django 6.1.1 on 2026-09-25 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genai_pipeline', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='genaianalysis',
            name='cache_hit_tokens',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
