"""
Django settings for support_nova_project project.

Generated by 'django-admin startproject' using Django 6.1.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.1/ref/settings/
"""

import os
import sys
from pathlib import Path

from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Secrets live in the repo-root .env file (never committed).
load_dotenv(BASE_DIR.parent / '.env')


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.1/howto/deployment/checklist/

# Vercel sets VERCEL=1 in its builds and functions. Everything Vercel-specific below keys off it,
# so local development behaves exactly as before.
ON_VERCEL = bool(os.getenv('VERCEL'))
# Where the app may write files. On Vercel only /tmp is writable, and it does not survive a cold
# start: uploads and saved emails there are temporary (use object storage for lasting files).
WRITABLE_DIR = Path('/tmp') if ON_VERCEL else BASE_DIR

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('DJANGO_SECRET_KEY') or 'django-insecure-dev-only-change-me'
if ON_VERCEL and SECRET_KEY.startswith('django-insecure'):
    from django.core.exceptions import ImproperlyConfigured
    raise ImproperlyConfigured('Set DJANGO_SECRET_KEY in the Vercel project environment variables.')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DJANGO_DEBUG', 'false' if ON_VERCEL else 'true').lower() == 'true'

# Comma-separated extra hosts, e.g. a custom domain. *.vercel.app is always allowed on Vercel.
ALLOWED_HOSTS = [h.strip() for h in os.getenv('DJANGO_ALLOWED_HOSTS', '').split(',') if h.strip()]
if ON_VERCEL:
    ALLOWED_HOSTS += ['.vercel.app']
CSRF_TRUSTED_ORIGINS = [f'https://{h.lstrip(".")}' for h in ALLOWED_HOSTS if h != '.vercel.app'] + (
    ['https://*.vercel.app'] if ON_VERCEL else [])
if ON_VERCEL:
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # SupportNova apps
    'accounts',
    'catalog',
    'knowledge_base',
    'rules',
    'complaints',
    'genai_pipeline',
    'python_validation',
    'workflow',
    'reports',
    'complaint_dataset',
]

AUTH_USER_MODEL = 'accounts.User'

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'support_nova_project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'support_nova_project.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}
# Hosted Postgres (e.g. Neon from the Vercel Marketplace, which sets DATABASE_URL). Vercel's disk is
# read-only and temporary, so SQLite cannot be used there.
if os.getenv('DATABASE_URL'):
    from urllib.parse import parse_qsl, unquote, urlparse

    _db = urlparse(os.environ['DATABASE_URL'])
    DATABASES['default'] = {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': _db.path.lstrip('/'),
        'USER': unquote(_db.username or ''),
        'PASSWORD': unquote(_db.password or ''),
        'HOST': _db.hostname,
        'PORT': _db.port or 5432,
        'OPTIONS': {'sslmode': 'require', **dict(parse_qsl(_db.query))},
        'CONN_MAX_AGE': 60,
        'CONN_HEALTH_CHECKS': True,
    }


# Password hashing: Argon2 first (strong and ~100x faster to check than PBKDF2 at Django's 1.5M
# iterations, which made every sign-in take seconds). Older PBKDF2 hashes still verify and are
# upgraded to Argon2 automatically at the user's next sign-in.
PASSWORD_HASHERS = [
    'django.contrib.auth.hashers.Argon2PasswordHasher',
    'django.contrib.auth.hashers.PBKDF2PasswordHasher',
    'django.contrib.auth.hashers.PBKDF2SHA1PasswordHasher',
]


# Password validation
# https://docs.djangoproject.com/en/6.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

# Local time for dates shown in reports and for grouping complaints by day (the UI shows browser time).
TIME_ZONE = os.getenv('TIME_ZONE', 'Asia/Karachi')

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.1/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'  # Vercel runs collectstatic and serves these from its CDN

# Uploaded files (knowledge-base documents)
MEDIA_URL = 'media/'
MEDIA_ROOT = WRITABLE_DIR / 'media'
# Vercel accepts request bodies up to 4.5 MB, so uploads are capped at 4 MB there.
KB_MAX_UPLOAD_MB = int(os.getenv('KB_MAX_UPLOAD_MB', 4 if ON_VERCEL else 10))


# Email
# https://docs.djangoproject.com/en/6.1/topics/email/#topic-email-configuration



# Fast (insecure) hashing only while running tests, so the suite doesn't crawl.
if 'test' in sys.argv:
    PASSWORD_HASHERS = ['django.contrib.auth.hashers.MD5PasswordHasher']


# Embeddings + FAISS vector search (duplicate / repeat detection, semantic policy retrieval)
# 'fastembed' = real local model (downloaded once to models_cache/); 'hashing' = tiny offline
# fallback used by the test suite (no download, not semantic).
EMBEDDING_BACKEND = os.getenv('EMBEDDING_BACKEND', 'fastembed')
if 'test' in sys.argv:
    EMBEDDING_BACKEND = 'hashing'  # tests must not download a model
EMBEDDING_MODEL = os.getenv('EMBEDDING_MODEL', 'BAAI/bge-small-en-v1.5')
EMBEDDING_CACHE_DIR = WRITABLE_DIR / 'models_cache'  # on Vercel: downloaded once per cold start
# Cosine similarity thresholds for bge-small. First calibrated on 16 hand-written pairs, then
# re-tuned on the dataset's dev split (41 same-customer pairs): resubmitted near-duplicates
# 0.971-0.999, reworded follow-ups (repeats) 0.818-0.969, unrelated complaints 0.525-0.817.
#   >= NEAR_DUPLICATE_THRESHOLD and the first is still open -> near-duplicate
#   >= REPEAT_CERTAIN_THRESHOLD                      -> repeat
#   >= REPEAT_COMPLAINT_THRESHOLD and the keyword classifier does not put the two complaints
#      in different subcategories                    -> repeat
NEAR_DUPLICATE_THRESHOLD = float(os.getenv('NEAR_DUPLICATE_THRESHOLD', 0.97))
REPEAT_CERTAIN_THRESHOLD = float(os.getenv('REPEAT_CERTAIN_THRESHOLD', 0.85))
REPEAT_COMPLAINT_THRESHOLD = float(os.getenv('REPEAT_COMPLAINT_THRESHOLD', 0.75))
# An identical complaint re-submitted within this many days while the first is still open is rejected.
DUPLICATE_WINDOW_DAYS = int(os.getenv('DUPLICATE_WINDOW_DAYS', 7))
COMPLAINT_MAX_ATTACHMENT_MB = int(os.getenv('COMPLAINT_MAX_ATTACHMENT_MB', 4 if ON_VERCEL else 5))


# JWT authentication
JWT_SECRET_KEY = os.getenv('JWT_SECRET_KEY', SECRET_KEY)
JWT_ALGORITHM = 'HS256'
JWT_ACCESS_TOKEN_MINUTES = int(os.getenv('JWT_ACCESS_TOKEN_MINUTES', 60))
JWT_REFRESH_TOKEN_DAYS = int(os.getenv('JWT_REFRESH_TOKEN_DAYS', 7))


# GenAI provider (DeepSeek, OpenAI-compatible)
DEEPSEEK_BASE_URL = os.getenv('DEEPSEEK_BASE_URL', 'https://api.deepseek.com')
DEEPSEEK_API_KEY = os.getenv('DEEPSEEK_API_KEY', '')
DEEPSEEK_MODEL = os.getenv('DEEPSEEK_MODEL', 'deepseek-flash')

# Pipeline 1 generation settings (logged with every analysis as "generation configuration")
GENAI_PROVIDER = 'deepseek'
# deepseek-flash reasons ("thinks") before answering by default: disabled | low | high.
# Reasoning tokens count against GENAI_MAX_TOKENS, and temperature only applies when disabled.
GENAI_THINKING = os.getenv('GENAI_THINKING', 'disabled')
GENAI_TEMPERATURE = float(os.getenv('GENAI_TEMPERATURE', 0.2))  # low = consistent classification
GENAI_MAX_TOKENS = int(os.getenv('GENAI_MAX_TOKENS', 3000))  # enough that the JSON is never cut off
GENAI_MAX_ATTEMPTS = int(os.getenv('GENAI_MAX_ATTEMPTS', 3))  # 1 call + 2 controlled retries
GENAI_TIMEOUT_SECONDS = int(os.getenv('GENAI_TIMEOUT_SECONDS', 45))
GENAI_RETRY_BACKOFF_SECONDS = float(os.getenv('GENAI_RETRY_BACKOFF_SECONDS', 1))
GENAI_POLICY_CHUNKS = int(os.getenv('GENAI_POLICY_CHUNKS', 8))  # policy excerpts given to the model
# Short documents always included in the prompt (cached prefix): escalation triggers, SLA priorities, routing.
GENAI_STANDING_POLICIES = ['ESC-SOP', 'SLA-POL', 'RTG-RUL']
GENAI_DEFAULT_TONE = os.getenv('GENAI_DEFAULT_TONE', 'empathetic')
# Run GenAI analysis + validation + routing automatically right after a complaint is submitted.
# Off in the test suite, so tests never call the real GenAI API.
AUTO_PROCESS_ON_SUBMIT = os.getenv('AUTO_PROCESS_ON_SUBMIT', 'true').lower() == 'true'
if 'test' in sys.argv:
    AUTO_PROCESS_ON_SUBMIT = False

# SLA used while a complaint has no priority yet (e.g. unclassifiable and the GenAI call failed)
DEFAULT_SLA_PRIORITY = os.getenv('DEFAULT_SLA_PRIORITY', 'P2')

# Pipeline 2 thresholds
VALIDATION_REVIEW_SCORE = int(os.getenv('VALIDATION_REVIEW_SCORE', 70))  # below this -> manual review
# Calibrated on real outputs: reworded-but-covered actions 0.72-0.98, a truly missing action 0.63.
REQUIRED_ACTION_SIMILARITY = float(os.getenv('REQUIRED_ACTION_SIMILARITY', 0.70))
PROHIBITED_ACTION_SIMILARITY = float(os.getenv('PROHIBITED_ACTION_SIMILARITY', 0.85))

# Fixed app-level id sent to DeepSeek (never a customer id: the context cache is isolated per user_id).
GENAI_USER_ID = os.getenv('GENAI_USER_ID', 'supportnova-pipeline1')

# Email to customers (SMTP) and reading their replies from the support inbox (IMAP, manage.py fetch_emails).
# Without EMAIL_HOST nothing is sent: each email is saved as a file in sent_emails/ instead.
SMTP_HOST = os.getenv('EMAIL_HOST', '')
SMTP_USER = os.getenv('EMAIL_HOST_USER', '')
SMTP_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD', '')
if SMTP_HOST:
    MAILERS = {'default': {'BACKEND': 'django.core.mail.backends.smtp.EmailBackend', 'OPTIONS': {
        'host': SMTP_HOST,
        'port': int(os.getenv('EMAIL_PORT', 587)),
        'username': SMTP_USER,
        'password': SMTP_PASSWORD,
        'use_tls': os.getenv('EMAIL_USE_TLS', 'true').lower() == 'true',
        'timeout': 20,
    }}}
else:
    MAILERS = {'default': {'BACKEND': 'django.core.mail.backends.filebased.EmailBackend',
                           'OPTIONS': {'file_path': WRITABLE_DIR / 'sent_emails'}}}
DEFAULT_FROM_EMAIL = os.getenv('DEFAULT_FROM_EMAIL', 'Lumora Support <support@lumora.example>')
IMAP_HOST = os.getenv('IMAP_HOST', '')
IMAP_PORT = int(os.getenv('IMAP_PORT', 993))
IMAP_USER = os.getenv('IMAP_USER', '') or SMTP_USER
IMAP_PASSWORD = os.getenv('IMAP_PASSWORD', '') or SMTP_PASSWORD
IMAP_FOLDER = os.getenv('IMAP_FOLDER', 'INBOX')
# Where customers open their complaint (used for the link in emails)
FRONTEND_URL = os.getenv('FRONTEND_URL', 'http://localhost:5173')
