"""
Django settings for support_nova_project project.

Generated by 'django-admin startproject' using Django 6.1.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.1/ref/settings/
"""

import os
import sys
from pathlib import Path

from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Secrets live in the repo-root .env file (never committed).
load_dotenv(BASE_DIR.parent / '.env')


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('DJANGO_SECRET_KEY', 'django-insecure-dev-only-change-me')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # SupportNova apps
    'accounts',
    'catalog',
    'knowledge_base',
    'rules',
    'complaints',
    'genai_pipeline',
    'python_validation',
    'workflow',
    'reports',
    'complaint_dataset',
]

AUTH_USER_MODEL = 'accounts.User'

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'support_nova_project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'support_nova_project.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.1/howto/static-files/

STATIC_URL = 'static/'

# Uploaded files (knowledge-base documents)
MEDIA_URL = 'media/'
MEDIA_ROOT = BASE_DIR / 'media'
KB_MAX_UPLOAD_MB = int(os.getenv('KB_MAX_UPLOAD_MB', 10))


# Email
# https://docs.djangoproject.com/en/6.1/topics/email/#topic-email-configuration

MAILERS = {
    'default': {
        'BACKEND': 'django.core.mail.backends.console.EmailBackend',
    },
}


# Fast (insecure) hashing only while running tests, so the suite doesn't crawl.
if 'test' in sys.argv:
    PASSWORD_HASHERS = ['django.contrib.auth.hashers.MD5PasswordHasher']


# Embeddings + FAISS vector search (duplicate / repeat detection, semantic policy retrieval)
# 'fastembed' = real local model (downloaded once to models_cache/); 'hashing' = tiny offline
# fallback used by the test suite (no download, not semantic).
EMBEDDING_BACKEND = os.getenv('EMBEDDING_BACKEND', 'fastembed')
if 'test' in sys.argv:
    EMBEDDING_BACKEND = 'hashing'  # tests must not download a model
EMBEDDING_MODEL = os.getenv('EMBEDDING_MODEL', 'BAAI/bge-small-en-v1.5')
EMBEDDING_CACHE_DIR = BASE_DIR / 'models_cache'
# Cosine similarity thresholds for bge-small. First calibrated on 16 hand-written pairs, then
# re-tuned on the dataset's dev split (41 same-customer pairs): resubmitted near-duplicates
# 0.971-0.999, reworded follow-ups (repeats) 0.818-0.969, unrelated complaints 0.525-0.817.
#   >= NEAR_DUPLICATE_THRESHOLD and the first is still open -> near-duplicate
#   >= REPEAT_CERTAIN_THRESHOLD                      -> repeat
#   >= REPEAT_COMPLAINT_THRESHOLD and the keyword classifier does not put the two complaints
#      in different subcategories                    -> repeat
NEAR_DUPLICATE_THRESHOLD = float(os.getenv('NEAR_DUPLICATE_THRESHOLD', 0.97))
REPEAT_CERTAIN_THRESHOLD = float(os.getenv('REPEAT_CERTAIN_THRESHOLD', 0.85))
REPEAT_COMPLAINT_THRESHOLD = float(os.getenv('REPEAT_COMPLAINT_THRESHOLD', 0.75))
# An identical complaint re-submitted within this many days while the first is still open is rejected.
DUPLICATE_WINDOW_DAYS = int(os.getenv('DUPLICATE_WINDOW_DAYS', 7))
COMPLAINT_MAX_ATTACHMENT_MB = int(os.getenv('COMPLAINT_MAX_ATTACHMENT_MB', 5))


# JWT authentication
JWT_SECRET_KEY = os.getenv('JWT_SECRET_KEY', SECRET_KEY)
JWT_ALGORITHM = 'HS256'
JWT_ACCESS_TOKEN_MINUTES = int(os.getenv('JWT_ACCESS_TOKEN_MINUTES', 60))
JWT_REFRESH_TOKEN_DAYS = int(os.getenv('JWT_REFRESH_TOKEN_DAYS', 7))


# GenAI provider (DeepSeek, OpenAI-compatible)
DEEPSEEK_BASE_URL = os.getenv('DEEPSEEK_BASE_URL', 'https://api.deepseek.com')
DEEPSEEK_API_KEY = os.getenv('DEEPSEEK_API_KEY', '')
DEEPSEEK_MODEL = os.getenv('DEEPSEEK_MODEL', 'deepseek-flash')

# Pipeline 1 generation settings (logged with every analysis as "generation configuration")
GENAI_PROVIDER = 'deepseek'
# deepseek-flash reasons ("thinks") before answering by default: disabled | low | high.
# Reasoning tokens count against GENAI_MAX_TOKENS, and temperature only applies when disabled.
GENAI_THINKING = os.getenv('GENAI_THINKING', 'disabled')
GENAI_TEMPERATURE = float(os.getenv('GENAI_TEMPERATURE', 0.2))  # low = consistent classification
GENAI_MAX_TOKENS = int(os.getenv('GENAI_MAX_TOKENS', 3000))  # enough that the JSON is never cut off
GENAI_MAX_ATTEMPTS = int(os.getenv('GENAI_MAX_ATTEMPTS', 3))  # 1 call + 2 controlled retries
GENAI_TIMEOUT_SECONDS = int(os.getenv('GENAI_TIMEOUT_SECONDS', 45))
GENAI_RETRY_BACKOFF_SECONDS = float(os.getenv('GENAI_RETRY_BACKOFF_SECONDS', 1))
GENAI_POLICY_CHUNKS = int(os.getenv('GENAI_POLICY_CHUNKS', 8))  # policy excerpts given to the model
# Short documents always included in the prompt (cached prefix): escalation triggers, SLA priorities, routing.
GENAI_STANDING_POLICIES = ['ESC-SOP', 'SLA-POL', 'RTG-RUL']
GENAI_DEFAULT_TONE = os.getenv('GENAI_DEFAULT_TONE', 'empathetic')
# Run GenAI analysis + validation + routing automatically right after a complaint is submitted.
# Off in the test suite, so tests never call the real GenAI API.
AUTO_PROCESS_ON_SUBMIT = os.getenv('AUTO_PROCESS_ON_SUBMIT', 'true').lower() == 'true'
if 'test' in sys.argv:
    AUTO_PROCESS_ON_SUBMIT = False

# SLA used while a complaint has no priority yet (e.g. unclassifiable and the GenAI call failed)
DEFAULT_SLA_PRIORITY = os.getenv('DEFAULT_SLA_PRIORITY', 'P2')

# Pipeline 2 thresholds
VALIDATION_REVIEW_SCORE = int(os.getenv('VALIDATION_REVIEW_SCORE', 70))  # below this -> manual review
# Calibrated on real outputs: reworded-but-covered actions 0.72-0.98, a truly missing action 0.63.
REQUIRED_ACTION_SIMILARITY = float(os.getenv('REQUIRED_ACTION_SIMILARITY', 0.70))
PROHIBITED_ACTION_SIMILARITY = float(os.getenv('PROHIBITED_ACTION_SIMILARITY', 0.85))

# Fixed app-level id sent to DeepSeek (never a customer id: the context cache is isolated per user_id).
GENAI_USER_ID = os.getenv('GENAI_USER_ID', 'supportnova-pipeline1')
