# Generated by Django 6.1.1 on 2026-09-25 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcategory',
            name='keywords',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
