# Generated by Django 6.1.1 on 2026-09-26 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcategory',
            name='is_fallback',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='takes_precedence_over',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
