# Generated by Django 6.1.1 on 2026-09-25 11:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PolicyDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_id', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=200)),
                ('doc_type', models.CharField(choices=[('policy', 'Policy'), ('compliance', 'Compliance Guideline'), ('sla', 'Service Level Agreement'), ('routing', 'Department Routing Rules'), ('sop', 'Standard Operating Procedure'), ('template', 'Response Template'), ('faq', 'FAQ'), ('other', 'Other')], max_length=20)),
                ('version', models.CharField(max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('previous', 'Previous'), ('superseded', 'Superseded'), ('draft', 'Draft')], default='draft', max_length=20)),
                ('effective_date', models.DateField()),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('file', models.FileField(upload_to='kb/%Y/%m/')),
                ('original_filename', models.CharField(max_length=255)),
                ('file_size', models.PositiveIntegerField()),
                ('file_hash', models.CharField(max_length=64, unique=True)),
                ('page_count', models.PositiveIntegerField(blank=True, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='catalog.category')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['doc_id', '-effective_date'],
            },
        ),
        migrations.CreateModel(
            name='PolicyChunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chunk_id', models.CharField(max_length=100, unique=True)),
                ('order', models.PositiveIntegerField()),
                ('section', models.CharField(blank=True, max_length=20)),
                ('heading', models.CharField(blank=True, max_length=255)),
                ('page', models.PositiveIntegerField(blank=True, null=True)),
                ('text', models.TextField()),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='knowledge_base.policydocument')),
            ],
            options={
                'ordering': ['document', 'order'],
            },
        ),
        migrations.AddConstraint(
            model_name='policydocument',
            constraint=models.UniqueConstraint(fields=('doc_id', 'version'), name='unique_doc_version'),
        ),
    ]
