# Generated by Django 6.1.1 on 2026-09-25 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge_base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='policychunk',
            name='embedding',
            field=models.BinaryField(null=True),
        ),
    ]
