# Generated by Django 6.1.1 on 2026-09-25 11:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0002_subcategory_keywords'),
    ]

    operations = [
        migrations.CreateModel(
            name='EscalationRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule_id', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=150)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('conditions', models.JSONField(default=dict)),
                ('escalation_level', models.CharField(choices=[('none', 'No Escalation'), ('supervisor', 'Supervisor Review'), ('department_manager', 'Department Manager'), ('specialist_team', 'Specialist Team'), ('compliance_review', 'Compliance Review'), ('critical_management', 'Critical Management Escalation')], max_length=30)),
                ('min_urgency', models.CharField(blank=True, choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High'), ('Critical', 'Critical')], max_length=10)),
                ('min_priority', models.CharField(blank=True, choices=[('P0', 'P0 - Critical'), ('P1', 'P1 - High'), ('P2', 'P2 - Medium'), ('P3', 'P3 - Low')], max_length=2)),
                ('policy_id', models.CharField(blank=True, max_length=50)),
                ('policy_section', models.CharField(blank=True, max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('target_department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='escalation_rules', to='catalog.department')),
            ],
            options={
                'ordering': ['rule_id'],
            },
        ),
        migrations.CreateModel(
            name='ResolutionRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule_id', models.CharField(max_length=20, unique=True)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('conditions', models.JSONField(blank=True, default=dict)),
                ('urgency', models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High'), ('Critical', 'Critical')], max_length=10)),
                ('priority', models.CharField(choices=[('P0', 'P0 - Critical'), ('P1', 'P1 - High'), ('P2', 'P2 - Medium'), ('P3', 'P3 - Low')], max_length=2)),
                ('escalation_level', models.CharField(choices=[('none', 'No Escalation'), ('supervisor', 'Supervisor Review'), ('department_manager', 'Department Manager'), ('specialist_team', 'Specialist Team'), ('compliance_review', 'Compliance Review'), ('critical_management', 'Critical Management Escalation')], default='none', max_length=30)),
                ('policy_id', models.CharField(max_length=50)),
                ('policy_section', models.CharField(blank=True, max_length=20)),
                ('required_actions', models.JSONField(blank=True, default=list)),
                ('prohibited_actions', models.JSONField(blank=True, default=list)),
                ('allowed_compensation', models.JSONField(blank=True, default=list)),
                ('follow_up_days', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='resolution_rules', to='catalog.category')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='resolution_rules', to='catalog.department')),
                ('subcategory', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='resolution_rules', to='catalog.subcategory')),
                ('supporting_departments', models.ManyToManyField(blank=True, related_name='supporting_rules', to='catalog.department')),
            ],
            options={
                'ordering': ['rule_id'],
            },
        ),
    ]
