# Generated by Django 6.1.1 on 2026-09-25 12:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0003_product'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complaint_id', models.CharField(blank=True, max_length=20, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('customer_type', models.CharField(max_length=20)),
                ('channel', models.CharField(choices=[('web', 'Web form'), ('email', 'E-mail'), ('chat', 'Chat'), ('upload', 'Uploaded complaint')], default='web', max_length=10)),
                ('preferred_contact', models.CharField(choices=[('email', 'E-mail'), ('phone', 'Phone'), ('chat', 'Chat')], default='email', max_length=10)),
                ('requested_resolution', models.CharField(blank=True, max_length=500)),
                ('supporting_information', models.TextField(blank=True)),
                ('normalized_text', models.TextField()),
                ('text_hash', models.CharField(db_index=True, max_length=64)),
                ('extracted_metadata', models.JSONField(default=dict)),
                ('security_flags', models.JSONField(default=list)),
                ('intake_warnings', models.JSONField(default=list)),
                ('embedding', models.BinaryField(null=True)),
                ('match_type', models.CharField(blank=True, choices=[('', 'None'), ('near_duplicate', 'Near-duplicate'), ('repeat', 'Repeat of an earlier complaint')], default='', max_length=20)),
                ('similarity', models.FloatField(blank=True, null=True)),
                ('previous_related_count', models.PositiveSmallIntegerField(default=0)),
                ('facts', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('new', 'New'), ('analyzed', 'Analyzed'), ('assigned', 'Assigned'), ('in_progress', 'In Progress'), ('awaiting_customer', 'Awaiting Customer'), ('escalated', 'Escalated'), ('resolved', 'Resolved'), ('closed', 'Closed'), ('reopened', 'Reopened')], default='new', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='complaints', to=settings.AUTH_USER_MODEL)),
                ('previous_complaint', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='follow_up_complaints', to='complaints.complaint')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='complaints', to='catalog.product')),
                ('related_complaint', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='later_related_complaints', to='complaints.complaint')),
                ('submitted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='complaints_submitted', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ComplaintAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='complaints/%Y/%m/')),
                ('original_filename', models.CharField(max_length=255)),
                ('content_type', models.CharField(max_length=100)),
                ('file_size', models.PositiveIntegerField()),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('complaint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='complaints.complaint')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_ref', models.CharField(max_length=20, unique=True)),
                ('quantity', models.PositiveSmallIntegerField(default=1)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('express', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('processing', 'Processing'), ('shipped', 'Shipped'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], max_length=20)),
                ('order_date', models.DateField()),
                ('estimated_delivery_date', models.DateField(blank=True, null=True)),
                ('delivery_date', models.DateField(blank=True, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='catalog.product')),
            ],
            options={
                'ordering': ['-order_date'],
            },
        ),
        migrations.AddField(
            model_name='complaint',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='complaints', to='complaints.order'),
        ),
    ]
