# Generated by Django 6.1.1 on 2026-09-25 14:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_product'),
        ('complaints', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_complaints', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='complaint',
            name='awaiting_since',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='complaint',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='complaints', to='catalog.category'),
        ),
        migrations.AddField(
            model_name='complaint',
            name='closed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='complaint',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='complaints', to='catalog.department'),
        ),
        migrations.AddField(
            model_name='complaint',
            name='escalation_level',
            field=models.CharField(blank=True, default='none', max_length=30),
        ),
        migrations.AddField(
            model_name='complaint',
            name='first_response_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='complaint',
            name='follow_up_done_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='complaint',
            name='follow_up_due',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='complaint',
            name='priority',
            field=models.CharField(blank=True, choices=[('P0', 'P0 - Critical'), ('P1', 'P1 - High'), ('P2', 'P2 - Medium'), ('P3', 'P3 - Low')], max_length=2),
        ),
        migrations.AddField(
            model_name='complaint',
            name='resolution',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='complaint',
            name='resolved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='complaint',
            name='response_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='complaint',
            name='response_text',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='complaint',
            name='review_status',
            field=models.CharField(choices=[('not_required', 'Not required'), ('pending', 'Pending review'), ('approved', 'Approved'), ('rejected', 'Recommendation rejected')], default='not_required', max_length=20),
        ),
        migrations.AddField(
            model_name='complaint',
            name='sentiment',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='complaint',
            name='sla_paused_seconds',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='complaint',
            name='sla_resolution_due',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='complaint',
            name='sla_response_due',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='complaint',
            name='subcategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='complaints', to='catalog.subcategory'),
        ),
        migrations.AddField(
            model_name='complaint',
            name='supporting_departments',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='complaint',
            name='urgency',
            field=models.CharField(blank=True, choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High'), ('Critical', 'Critical')], max_length=10),
        ),
        migrations.AddField(
            model_name='complaint',
            name='verification_score',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='complaint',
            name='verification_status',
            field=models.CharField(choices=[('pending', 'Not processed yet'), ('verified', 'Verified'), ('manual_review', 'Manual Review')], default='pending', max_length=20),
        ),
    ]
