# Generated by Django 6.1.1 on 2026-09-25 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0002_complaint_assigned_to_complaint_awaiting_since_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='sla_clock_start',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
